# [START cloudbuild_quickstart_build]
steps:
  # -------------------- Build docker image from dockerfile in the root of the repo ---------------------------------
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - build
      - '--no-cache'
      - '-t'
      - '$LOCATION-docker.pkg.dev/$PROJECT_ID/chatty-backend-service/chatty-backend-service:$COMMIT_SHA'
      - .
      - '-f'
      - Dockerfile
    id: 'build'
    secretEnv:
      - DATABASE_URL
      - ALGOLIA_APP_ID
      - ALGOLIA_API_KEY
      - REDIS_USERNAME
      - REDIS_PASSWORD
      - REDIS_HOST
      - JWT_SECRET
      - OPEN_AI_API_KEY
      - REDIS_TTL

  # -------------------- Push to google repo ---------------------------------
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$LOCATION-docker.pkg.dev/$PROJECT_ID/chatty-backend-service/chatty-backend-service:$COMMIT_SHA'
    id: 'push'

  # -------------------- Deploy ---------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - note-app-react
      - '--platform=managed'
      - '--image=$LOCATION-docker.pkg.dev/$PROJECT_ID/chatty-backend-service/chatty-backend-service:$COMMIT_SHA'
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
    waitFor: ['push']
images:
  - '$LOCATION-docker.pkg.dev/$PROJECT_ID/chatty-backend-service/chatty-backend-service:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: ALLOW_LOOSE
substitutions:
  _DEPLOY_REGION: europe-west1
  _GCR_HOSTNAME: eu.gcr.io
  _PLATFORM: managed
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - chatty-backend-service

availableSecrets:
  secretManager:
    - versionName: 'projects/$PROJECT_ID/secrets/VERSION/versions/1'
      env: 'DATABASE_URL'
    - versionName: 'projects/$PROJECT_ID/secrets/SERVICE_NAME/versions/1'
      env: 'ALGOLIA_APP_ID'
    - versionName: 'projects/$PROJECT_ID/secrets/DB_CONNECTION_STRING/versions/1'
      env: 'ALGOLIA_API_KEY'
    - versionName: 'projects/$PROJECT_ID/secrets/TEST_DB_CONNECTION_STRING/versions/1'
      env: 'REDIS_USERNAME'
    - versionName: 'projects/$PROJECT_ID/secrets/FIREBASE_APIKEY/versions/1'
      env: 'REDIS_PASSWORD'
    - versionName: 'projects/$PROJECT_ID/secrets/FIREBASE_AUTHDOMAIN/versions/1'
      env: 'REDIS_HOST'
    - versionName: 'projects/$PROJECT_ID/secrets/FIREBASE_PROJECTID/versions/1'
      env: 'JWT_SECRET'
    - versionName: 'projects/$PROJECT_ID/secrets/FIREBASE_STORAGEBUCKET/versions/1'
      env: 'OPEN_AI_API_KEY'
    - versionName: 'projects/$PROJECT_ID/secrets/FIREBASE_MESSAGINGSENDERID/versions/1'
      env: 'REDIS_TTL'
# [END cloudbuild_quickstart_build]